esphome:
  name: smart-coffee
  friendly_name: Smart Coffee
esp32:
  board: esp32-c3-devkitm-1 
  framework:
    type: arduino
logger:
ota:
  - platform: esphome
api:
  encryption:
    key: "Lp+LTvWRUSR1GwkPOZDIKzU6U3pabS3uDgAq7qVCD+c="
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Smart-Coffee Fallback Hotspot"
    password: "wCm3KgdrcqjU"
captive_portal:
#SETUP END

one_wire:
  - platform: gpio
    pin: GPIO1
sensor:
  - platform: dallas_temp
    name: temperature
    id: temperature
    update_interval: 1s


# hot switch and pump
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO2
      inverted: True
      mode: 
        pullup: True
        input: True
    name: HOTSW
    on_release: 
      then:
        - switch.turn_off: PUMP
        - light.turn_off: rgbled_state

    on_press: 
      then:
        - switch.turn_on: PUMP
        - light.turn_on: 
            id: rgbled_state
            red: 0%
            green: 20%
            blue: 65%

# cold switch and preheat sequene
  - platform: gpio
    pin:
      number: GPIO3
      inverted: True
      mode: 
        pullup: True
        input: True
    name: COLDSW
    on_press: 
      then:
        - light.turn_on: 
            id: rgbled_state
            red: 40%
            blue: 40%
            green: 0%
            effect: Fast Pulse


        - climate.control: 
            mode: HEAT
            target_temperature: 85
            id: thermostat1
        
            
#capsule detection
  - platform: gpio
    name: CAPSULEDET
    pin:
      number: GPIO0
      inverted: True
      mode: 
        pullup: True
        input: True
# pump heater and magnetic lock
switch:
  - platform: gpio
    pin: GPIO7
    id: HEAT
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO5
    id: PUMP
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin:
      number: GPIO4
      inverted: True

    name: Magnet Lock
    id: LOCK
    restore_mode: ALWAYS_OFF
# rgb led 
output:
  - platform: ledc
    id: red
    pin: GPIO10
  - platform: ledc
    id: green
    pin: GPIO9
  - platform: ledc
    id: blue
    pin: GPIO8
light:
  - platform: rgb
    blue: blue
    red: red
    green: green
    id: rgbled_state
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Slow Pulse"
          transition_length: 2s
          update_interval: 1s

#thermostat
  
climate:
  - platform: thermostat
    name: "Water Temp"
    id: thermostat1
    sensor: temperature
    min_heating_off_time: 1s
    min_heating_run_time: 1s
    on_boot_restore_from: default_preset
    min_idle_time: 1s
    heat_action:
      - switch.turn_on: HEAT
    idle_action:
      - switch.turn_off: HEAT
    default_preset: pof
    visual: 
      max_temperature: 95
      min_temperature: 0   
    preset:
      - name: pof
        default_target_temperature_low: 20 °C
    on_state:
      then:
      # auto power off
      - if:
          condition:
            and:
              - for:
                  time: 5min
                  condition:
                    lambda: return id(thermostat1).mode == climate::CLIMATE_MODE_HEAT;
              - lambda: return id(thermostat1).mode == climate::CLIMATE_MODE_HEAT;
          then:
            - climate.control:
                id: thermostat1
                mode: "OFF"
            - logger.log: "Turned off heating after 5 minutes of continuous operation"
            - light.turn_off: rgbled_state
      - if:
        # heated indicator
            condition:
              lambda: return id(thermostat1).current_temperature > 85;
            then:
              - light.turn_on:
                  id: rgbled_state
                  red: 100%  # Orange
                  green: 35%
                  blue: 0%
                  effect: Slow Pulse
            











# CODED BY A HAPPY FEMBOY

